//
//  ControlWorker.swift
//  Rover
//
//  Created by Aratech iOS on 23/2/18.
//  Copyright (c) 2018 Aratech iOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ControlWorker {
	
	func doSomeWork() { }
}
