//
//  ControlPresenter.swift
//  Rover
//
//  Created by Aratech iOS on 23/2/18.
//  Copyright (c) 2018 Aratech iOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ControlPresentationLogic {
	func presentSomething(response: Control.Something.Response)
}

class ControlPresenter: ControlPresentationLogic {
	weak var viewController: ControlDisplayLogic?
	
	// MARK: Logic
	
	func presentSomething(response: Control.Something.Response) {
		let viewModel = Control.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
