//
//  ControlInteractor.swift
//  Rover
//
//  Created by Aratech iOS on 23/2/18.
//  Copyright (c) 2018 Aratech iOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ControlBusinessLogic {
	func doSomething(request: Control.Something.Request)
}

protocol ControlDataStore {
	//var name: String { get set }
}

class ControlInteractor: ControlBusinessLogic, ControlDataStore {
	
	var presenter: ControlPresentationLogic?
	var worker: ControlWorker?
	//var name: String = ""
	
	// MARK: Logic
	
	func doSomething(request: Control.Something.Request) {
		worker = ControlWorker()
		worker?.doSomeWork()
		
		let response = Control.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
