//
//  ControlViewController.swift
//  Rover
//
//  Created by Aratech iOS on 23/2/18.
//  Copyright (c) 2018 Aratech iOS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ControlDisplayLogic: class {
	func displaySomething(viewModel: Control.Something.ViewModel)
}

class ControlViewController: UIViewController, ControlDisplayLogic {
	var interactor: ControlBusinessLogic?
	var router: (NSObjectProtocol & ControlRoutingLogic & ControlDataPassing)?
	
	// MARK: Life Cycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}
	
	// MARK: Setup
	
	private func setup() {
		let viewController = self
		let interactor = ControlInteractor()
		let presenter = ControlPresenter()
		let router = ControlRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		doSomething()
	}
	
	// MARK: Logic
	
	//@IBOutlet weak var nameTextField: UITextField!
	
	func doSomething() {
		let request = Control.Something.Request()
		interactor?.doSomething(request: request)
	}
	
	// MARK: - Display Logic
	
	func displaySomething(viewModel: Control.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}
}
